/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import datos.Paciente;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.GestorLogico;
import org.junit.Assert;

/**
 *
 * @author aarga
 */
public class Ventana extends javax.swing.JFrame {

    private GestorLogico miGestorLogico;
    private Paciente pacienteSeleccionado;

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        miGestorLogico = new GestorLogico();
        initComponents();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btEditar = new javax.swing.JButton();
        btGuardar = new javax.swing.JButton();
        cjDocumento = new javax.swing.JTextField();
        cjNombre = new javax.swing.JTextField();
        cjNumero = new javax.swing.JTextField();
        cjCorreo = new javax.swing.JTextField();
        cjFechaNacimiento = new javax.swing.JTextField();
        btBorrar = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablapacientes = new javax.swing.JTable();
        btNuevo = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablapacientes2 = new javax.swing.JTable();
        btSalir2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablapacientes1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        cjConsulta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cjEnfermedades = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cjAntecedentes = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cjDiagnostico = new javax.swing.JTextField();
        btSalir1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cjResultado = new javax.swing.JCheckBox();
        btNuevo2 = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Número de documento:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nombre completo:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Número de teléfono:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Correo electrónico:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Fecha de nacimiento:");

        btEditar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btGuardar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btGuardar.setText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        cjDocumento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cjNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cjNumero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cjCorreo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cjFechaNacimiento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btBorrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btBorrar.setText("Borrar");
        btBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBorrarActionPerformed(evt);
            }
        });

        btSalir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        tablapacientes.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tablapacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablapacientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablapacientes);

        btNuevo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btNuevo.setText("Nuevo");
        btNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cjCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(cjFechaNacimiento)
                    .addComponent(cjDocumento)
                    .addComponent(cjNombre)
                    .addComponent(cjNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(btEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(114, 114, 114))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cjDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btGuardar)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cjNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cjNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cjCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cjFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btNuevo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("1", jPanel1);

        jTabbedPane1.addTab("Ingresar Datos", jTabbedPane2);

        jScrollPane3.setViewportView(tablapacientes2);

        btSalir2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btSalir2.setText("Salir");
        btSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalir2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setText("Asignar Cita");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jTabbedPane3.addTab("2", jPanel2);

        jTabbedPane1.addTab("Asginar Cita", jTabbedPane3);

        tablapacientes1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tablapacientes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablapacientes1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablapacientes1);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Motivo de consulta:");

        jLabel7.setText("PACIENTES:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Enfermedades:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Antecedentes:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Diagnóstico:");

        btSalir1.setText("Salir");
        btSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalir1ActionPerformed(evt);
            }
        });

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("¿Resultado Crítico?");

        cjResultado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cjResultado.setText("SI");

        btNuevo2.setText("Nuevo");
        btNuevo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevo2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cjAntecedentes, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                            .addComponent(cjDiagnostico)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cjResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel7)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btSalir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btNuevo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(cjConsulta))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(43, 43, 43)
                                    .addComponent(cjEnfermedades)))
                            .addGap(10, 10, 10))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btNuevo2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(74, 74, 74))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cjConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cjEnfermedades, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cjAntecedentes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cjDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cjResultado))
                .addGap(40, 40, 40))
        );

        jTabbedPane4.addTab("3", jPanel3);

        jTabbedPane1.addTab("Valorar Paciente", jTabbedPane4);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 740, 530);

        setSize(new java.awt.Dimension(766, 576));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        this.salir();
    }//GEN-LAST:event_btSalirActionPerformed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        this.adicionarPaciente();
    }//GEN-LAST:event_btGuardarActionPerformed

    private void tablapacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablapacientesMouseClicked
        this.seleccionarPaciente();
    }//GEN-LAST:event_tablapacientesMouseClicked

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        this.editarPaciente();
    }//GEN-LAST:event_btEditarActionPerformed

    private void btBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBorrarActionPerformed
        this.borrarPaciente();
    }//GEN-LAST:event_btBorrarActionPerformed

    private void btNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevoActionPerformed
        nuevoPaciente();
    }//GEN-LAST:event_btNuevoActionPerformed

    private void btSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalir1ActionPerformed
        this.salir();
    }//GEN-LAST:event_btSalir1ActionPerformed

    private void btSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalir2ActionPerformed
        this.salir();
    }//GEN-LAST:event_btSalir2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        adicionarHistoriaClinica();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btNuevo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevo2ActionPerformed
        nuevoInfoPaciente();
    }//GEN-LAST:event_btNuevo2ActionPerformed

    private void tablapacientes1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablapacientes1MouseClicked
        seleccionarPaciente1();
    }//GEN-LAST:event_tablapacientes1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    private void adicionarPaciente() {
        String documento = cjDocumento.getText().isEmpty() ? "0" : cjDocumento.getText();
        String nombre = cjNombre.getText().isEmpty() ? "0" : cjNombre.getText();
        String telefono = cjNumero.getText().isEmpty() ? "0" : cjNumero.getText();
        String correo = cjCorreo.getText().isEmpty() ? "0" : cjCorreo.getText();
        String fechaNacimiento = cjFechaNacimiento.getText().isEmpty() ? "0" : cjFechaNacimiento.getText();

        Paciente p = new Paciente();
        p.setDocumentoIdentidad(Long.parseLong(documento));
        p.setNombreCompleto(nombre);
        p.setNumeroTelefono(Long.parseLong(telefono));
        p.setCorreoElectronico(correo);
        p.setFechaNacimiento(fechaNacimiento);

        boolean rta = miGestorLogico.adicionarPaciente(p);

        if (rta) {
            JOptionPane.showMessageDialog(this, "Se almacenó paciente", "Atención", JOptionPane.INFORMATION_MESSAGE);
            cargarDatos();
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "NO se almacenó paciente", "Atención", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void adicionarHistoriaClinica() {
        String motivoConsulta = cjConsulta.getText().isEmpty() ? "0" : cjConsulta.getText();
        String enfermedades = cjEnfermedades.getText().isEmpty() ? "0" : cjEnfermedades.getText();
        String antecedentes = cjAntecedentes.getText().isEmpty() ? "0" : cjAntecedentes.getText();
        String diagnostico = cjDiagnostico.getText().isEmpty() ? "0" : cjDiagnostico.getText();
        boolean resul = cjResultado.isSelected();

        Paciente p1 = new Paciente();
        p1.setMotivoConsulta(motivoConsulta);
        p1.setEnfermedades(enfermedades);
        p1.setAntecedentes(antecedentes);
        p1.setDiagnostico(diagnostico);
        p1.setResultado(resul);
        
        boolean rta = miGestorLogico.adicionarHistoriaClinica(p1);

        if (rta) {
            JOptionPane.showMessageDialog(this, "Se almacenó la información del paciente", "Atención", JOptionPane.INFORMATION_MESSAGE);
            
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "NO se almacenó la información del paciente", "Atención", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void editarPaciente() {
        if (pacienteSeleccionado == null) {
            return;
        }
        boolean rta = miGestorLogico.editarPaciente(pacienteSeleccionado);
        if (rta) {
            JOptionPane.showMessageDialog(this, "Se modificó el paciente", "Atención", JOptionPane.INFORMATION_MESSAGE);
            cargarDatos();
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "NO se modificó paciente", "Atención", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void borrarPaciente() {
        if (pacienteSeleccionado == null) {
            return;
        }
        boolean rta = miGestorLogico.borrarPaciente(pacienteSeleccionado);
        if (rta) {
            JOptionPane.showMessageDialog(this, "Se borró el paciente", "Atención", JOptionPane.INFORMATION_MESSAGE);
            cargarDatos();
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "NO se borró el paciente", "Atención", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void nuevoPaciente() {
        limpiar();
    }

    private void nuevoInfoPaciente() {
        limpiar();
    }

    private void salir() {
        System.exit(0);
    }

    private void cargarDatos() {

        ArrayList<Paciente> lista = miGestorLogico.getPacientes();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("# DOCUMENTO ");
        modelo.addColumn("NOMBRE COMPLETO ");
        modelo.addColumn("# TELÉFONO ");
        modelo.addColumn("EMAIL ");
        modelo.addColumn("FECHA NACIMIENTO ");

        for (Paciente paciente : lista) {

            Object[] datos = {
                paciente.getDocumentoIdentidad(),
                paciente.getNombreCompleto(),
                paciente.getNumeroTelefono(),
                paciente.getCorreoElectronico(),
                paciente.getFechaNacimiento(),
            };
            modelo.addRow(datos);
        }
        this.tablapacientes.setModel(modelo);
        this.tablapacientes1.setModel(modelo);
        this.tablapacientes2.setModel(modelo);
    }

    private void limpiar() {
        this.cjNombre.setText("");
        this.cjNumero.setText("");
        this.cjCorreo.setText("");
        this.cjFechaNacimiento.setText("");
        this.cjDocumento.setText("");
        this.cjConsulta.setText("");
        this.cjEnfermedades.setText("");
        this.cjAntecedentes.setText("");
        this.cjDiagnostico.setText("");
        this.cjResultado.setSelected(false);
    }

    private void seleccionarPaciente() {
        int fila = tablapacientes.getSelectedRow();
        Long DocumentoIdentidad = (Long) tablapacientes.getValueAt(fila, 0);
        pacienteSeleccionado = this.miGestorLogico.buscarPaciente(DocumentoIdentidad);

        this.cjDocumento.setText(pacienteSeleccionado.getDocumentoIdentidad() == null ? " " : pacienteSeleccionado.getDocumentoIdentidad().toString());
        this.cjNombre.setText(pacienteSeleccionado.getNombreCompleto() == null ? " " : pacienteSeleccionado.getNombreCompleto());
        this.cjNumero.setText(pacienteSeleccionado.getNumeroTelefono() == null ? " " : pacienteSeleccionado.getNumeroTelefono().toString());
        this.cjCorreo.setText(pacienteSeleccionado.getCorreoElectronico() == null ? " " : pacienteSeleccionado.getCorreoElectronico());
        this.cjFechaNacimiento.setText(pacienteSeleccionado.getFechaNacimiento() == null ? " " : pacienteSeleccionado.getFechaNacimiento());

    }

    private void seleccionarPaciente1() {
        int fila = tablapacientes1.getSelectedRow();
        Long DocumentoIdentidad = (Long) tablapacientes1.getValueAt(fila, 0);
        pacienteSeleccionado = this.miGestorLogico.buscarPaciente(DocumentoIdentidad);

        //this.cjDocumento.setText(pacienteSeleccionado.getDocumentoIdentidad() == null ? " " : pacienteSeleccionado.getDocumentoIdentidad().toString());
        this.cjConsulta.setText(pacienteSeleccionado.getMotivoConsulta() == null ? " " : pacienteSeleccionado.getMotivoConsulta());
        this.cjEnfermedades.setText(pacienteSeleccionado.getEnfermedades() == null ? " " : pacienteSeleccionado.getEnfermedades());
        this.cjAntecedentes.setText(pacienteSeleccionado.getAntecedentes() == null ? " " : pacienteSeleccionado.getAntecedentes());
        this.cjDiagnostico.setText(pacienteSeleccionado.getDiagnostico() == null ? " " : pacienteSeleccionado.getDiagnostico());
        this.cjResultado.setSelected(false);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBorrar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btNuevo;
    private javax.swing.JButton btNuevo2;
    private javax.swing.JButton btSalir;
    private javax.swing.JButton btSalir1;
    private javax.swing.JButton btSalir2;
    private javax.swing.JTextField cjAntecedentes;
    private javax.swing.JTextField cjConsulta;
    private javax.swing.JTextField cjCorreo;
    private javax.swing.JTextField cjDiagnostico;
    private javax.swing.JTextField cjDocumento;
    private javax.swing.JTextField cjEnfermedades;
    private javax.swing.JTextField cjFechaNacimiento;
    private javax.swing.JTextField cjNombre;
    private javax.swing.JTextField cjNumero;
    private javax.swing.JCheckBox cjResultado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable tablapacientes;
    private javax.swing.JTable tablapacientes1;
    private javax.swing.JTable tablapacientes2;
    // End of variables declaration//GEN-END:variables
}
